BN20-94
Everpoint/sGis pull request #111
Opened 2020-07-07 08:40 UTC by kre1z0

add drop shadow to polygon symbols

2020-07-07 09:17 UTC, Maximkaaa requested changes

2020-07-07 09:17 UTC, Maximkaaa commented on samples/code/symbols/Polygon_Symbol.ts
> +        new Polygon([
Примеры использования кода, чтобы быть полезными, должны фокусировать внимание на том, о чем данный конкретный пример. Поэтому пример, в котороым первые 2.5 тыс. строк - это входные данные, обычно не самые лучшие. Конечно, красивый полигон на карте - это приятно, но это не самое главное. Чтобы сделать этот пример лучше, стоит либо вынести входные полигоны в отдельный json файл, либо использовать простую геометрию, занимающую не больше нескольких строчек.

2020-07-07 09:17 UTC, Maximkaaa commented on source/painters/DomPainter/Canvas.ts
> +        drawLines(this._ctx)
В результате получилось, что линия с тенью будет рисоваться на канвас 3 раза, при этом совершенно непонятно зачем. Почему бы просто один раз не нарисовать линию с тенью сразу?

2020-07-07 09:17 UTC, Maximkaaa commented on source/painters/DomPainter/Canvas.ts
> +        function drawLines(ctx: CanvasRenderingContext2D, offsetX: number = 0, offsetY: number = 0) {
В чем смысл делать локальную функцию? Зачем здесь замыкание? Не логичнее ли бы было использовать приватный метод?

2020-07-07 09:17 UTC, Maximkaaa commented on source/renders/Poly.ts
> +    dropShadow?: string = null;
Сложные параметры передавать в виде строкового значения нельзя. Ты этим убиваешь весь смысл типизации, усложняешь читаемость кода, не даешь пользоваться твоим свойством без прочтения документации. Кроме того, в этом случае твой код должен всегда проверять, что переданное значение корректно (чего ты не делаешь).

Почему бы для параметров тени не ввести тип, включающий эти четыре поля, строго типизированные и задокументированные? Этот тип можно тогда использовать во всех символах и рендерах, где нужна тень.

2020-07-07 09:17 UTC, Maximkaaa commented on source/symbols/PolylineSymbol.ts
> +    dropShadow?: string
Это свойство лучше назвать просто shadow

2020-07-08 06:42 UTC, kre1z0 commented on samples/code/symbols/Polygon_Symbol.ts
> +        new Polygon([
перенёс в отдельный файл

2020-07-08 06:43 UTC, kre1z0 commented on source/painters/DomPainter/Canvas.ts
> +        drawLines(this._ctx)
Исправил

2020-07-08 06:45 UTC, kre1z0 commented on source/painters/DomPainter/Canvas.ts
> +        function drawLines(ctx: CanvasRenderingContext2D, offsetX: number = 0, offsetY: number = 0) {
Перенёс в отдельный приватный метод

2020-07-08 06:46 UTC, kre1z0 commented on source/renders/Poly.ts
> +    dropShadow?: string = null;
Создал тип shadow с 4 полями {offsetX offsetY blur color}

2020-07-08 06:46 UTC, kre1z0 commented on source/symbols/PolylineSymbol.ts
> +    dropShadow?: string
Переименовал dropShadow в shadow

2020-07-09 18:04 UTC, Maximkaaa commented on source/painters/DomPainter/Canvas.ts
> +        if (render === null) {
```suggestion
        if (render.shadow === null) {
```

2020-07-09 18:06 UTC, Maximkaaa requested changes
Один комментарий

2020-07-09 18:41 UTC, kre1z0 commented on source/painters/DomPainter/Canvas.ts
> +        if (render === null) {
исправил

2020-07-10 08:42 UTC, Maximkaaa approved these changes

2020-07-10 08:42 UTC, merged