[Feature] Angle field for Poly
Everpoint/sGis pull request #125
Opened 2020-09-28 13:28 UTC by js2me

@Maximkaaa @JasonZIglar

2020-09-29 10:20 UTC, JasonZIglar commented on source/symbols/point/Square.ts
> +    constructor(options: SquareSymbolConstructorParams = {}) {
Стало интересно, почему именно в это место перенес конструктор?

2020-09-29 10:55 UTC, JasonZIglar commented on source/symbols/point/Square.ts
> +    angle: number = 0;
Доку забыл

2020-09-29 10:55 UTC, JasonZIglar commented on source/symbols/point/Square.ts
> +    angle?: number
Доку забыл

2020-09-29 11:03 UTC, JasonZIglar commented on source/painters/DomPainter/Canvas.ts
> +        if (render.angle) {
Каждую перерисовку canvas вращается. Пока не запускал, потому что с форка неудобно. Это вообще работает?)

2020-09-29 11:11 UTC, JasonZIglar requested changes
Оставил комменты

2020-09-29 11:24 UTC, js2me commented on source/symbols/point/Square.ts
> +    constructor(options: SquareSymbolConstructorParams = {}) {
Просто потому что так удобнее, везде конструктор вверху, а здесь его пришлось искать в методах

2020-09-29 11:27 UTC, js2me commented on source/painters/DomPainter/Canvas.ts
> +        if (render.angle) {
Ну вообще, каждую перерисовку канвас сбрасывается и рисуется все заново)   
Конечно работает

2020-09-29 11:29 UTC, JasonZIglar commented on source/symbols/point/Square.ts
> +    constructor(options: SquareSymbolConstructorParams = {}) {
Может тогда сделать сначала поля класса, потом конструктор а потом методы? нет?

2020-09-29 12:06 UTC, JasonZIglar commented on source/painters/DomPainter/Canvas.ts
> +        if (render.angle) {
Точнее не так, каждый последующий PolyRenderer в слое вращает канвас

2020-10-01 07:54 UTC, js2me commented
@JasonZIglar поправил

2020-10-01 10:48 UTC, JasonZIglar commented on source/painters/DomPainter/Canvas.ts
> +            this._ctx.translate(centerX, centerY)
Ты переместил канвас, повернул его, затем переместил обратно, нарисовал элемент и перевернул канвас в противоположный угол. Действия в сумме должны давать 0. Попробуй проделать с листом бумаги на столе тоже самое))) и увидишь, что последующие символы будут рисоваться в другом месте. Нужно переместить точку вращения в центр канваса, повернуть его, нарисовать символ, повернуть обратно и вернуть точку вращения на место.

2020-10-01 21:59 UTC, js2me commented on source/painters/DomPainter/Canvas.ts
> +            this._ctx.translate(centerX, centerY)
Так лучше ?

2020-10-02 06:28 UTC, JasonZIglar commented on source/painters/DomPainter/Canvas.ts
> +            this._ctx.translate(centerX, centerY)
Не понятный комментарий. Что лучше?

2020-10-02 08:49 UTC, JasonZIglar approved these changes

2020-10-04 16:22 UTC, JasonZIglar commented on source/utils/math.ts
> +export function rotate(cx: number, cy: number, x: number, y: number, radians: number): [number, number] {
Напиши доку плиз, что там counterclockwise rotation  нужен positive angle, для clockwise negative

2020-10-05 10:56 UTC, merged